INSERT INTO Employee VALUES (1, 'Cristina Lyptratt', 'Tazz', 0, 42985, 'Quality Control Specialist');
INSERT INTO Employee VALUES (2, 'Kris Rawles', 'Zoonder', 1, 84357, 'Nurse Practicioner');
INSERT INTO Employee VALUES (3, 'Sarajane Fawthrop', 'Photolist', 0, 53222, 'VP Marketing');
INSERT INTO Employee VALUES (4, 'Dory Gilding', 'Skajo', 0, 21928, 'Project Manager');
INSERT INTO Employee VALUES (5, 'Latrena Burr', 'Tekfly', 1, 69543, 'Marketing Assistant');
INSERT INTO Employee VALUES (6, 'Anjanette Sterke', 'Buzzbean', 1, 42873, 'Software Engineer I');
INSERT INTO Employee VALUES (7, 'Humbert Duding', 'Skiba', 0, 44115, 'Assistant Manager');
INSERT INTO Employee VALUES (8, 'Atlante Faireclough', 'Twitterbeat', 1, 79959, 'Electrical Engineer');
INSERT INTO Employee VALUES (9, 'Hort Cove', 'Photojam', 1, 92954, 'Programmer Analyst II');
INSERT INTO Employee VALUES (10, 'Em Hannen', 'Fatz', 0, 75116, 'Software Engineer III');
INSERT INTO Employee VALUES (11, 'Jammie Cordsen', 'Dazzlesphere', 0, 94162, 'Technical Writer');
INSERT INTO Employee VALUES (12, 'Jefferson Sabine', 'Babbleopia', 0, 99866, 'Help Desk Technician');
INSERT INTO Employee VALUES (13, 'Willy Shorthouse', 'Skivee', 1, 16943, 'Staff Scientist');
INSERT INTO Employee VALUES (14, 'Zora Caesmans', 'Eazzy', 0, 54764, 'Senior Cost Accountant');
INSERT INTO Employee VALUES (15, 'Araldo McPherson', 'Fivechat', 1, 64847, 'Assistant Professor');
INSERT INTO Employee VALUES (16, 'Danette Brookes', 'Zoonoodle', 0, 70482, 'Sales Associate');
INSERT INTO Employee VALUES (17, 'Joey Trembath', 'Viva', 1, 96338, 'Research Nurse');
INSERT INTO Employee VALUES (18, 'Cherice Kenford', 'Voonix', 1, 56273, 'Junior Executive');
INSERT INTO Employee VALUES (19, 'Pooh Lehemann', 'Pixoboo', 1, 62574, 'Software Test Engineer IV');
INSERT INTO Employee VALUES (20, 'Aggie Purkins', 'Vipe', 0, 70875, 'Marketing Assistant');